# Site wide configuration

title: Computer Vision for the Web
description: "Computer Vision for the Web book practical examples."

# Site owner
owner:
  name: Foat Akhmadeev
  email: foat.akhmadeev@gmail.com
  web: https://foat.me
  twitter: foat_akhmadeev
  bio: "Software engineer and researcher."
  google:
    analytics: UA-62776233-1

exclude: ["README.md", ".editorconfig", ".gitignore"]
